config/routes.rb
Rails.application.routes.draw do
 
   # Routing 
   resources :users
   get 'signup', to: 'users#new', as: 'signup'
   get 'login', to: 'sessions#new', as: 'login'
   get 'afterlog', to: 'users#afterlog', as: 'afterlog'
   get 'home', to: 'users#home', as: 'home'

   # Root URL 
   root to: 'sessions#new'

   #For Logging in 
   post 'login', to: 'sessions#create'

   # Destroying  session , Logging Out
   delete 'logout', to: 'sessions#destroy', as: 'logout'


  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :require_user, :logged_in?

    def current_user  
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def require_user
      redirect_to login_path unless current_user
    end

    def logged_in?
    	if current_user
    		true
    	else 
    		false
    	end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user=User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password]) 
			session[:user_id]= @user.id 
			redirect_to afterlog_path
		else 
			redirect_to root_path
		end

	end

	def destroy
		session[:user_id]= nil
		redirect_to lol_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:afterlog]

	def new
		@user=User.new
	end

	def create
		@user=User.new(user_params)
		if @user.save
			session[:user_id]=@user.id 
			redirect_to afterlog_path
		else 
			redirect_to signup_path
		end

	end

	def afterlog
	end

	def home
	end


	private
	def user_params
		params.require(:user).permit(:first_name,:last_name,:email,:password)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Customauthsys</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-static-top">
  	<a class="navbar-brand" href="#">Custom Auth </a>
  	<ul class="nav navbar-nav">
  		<li class="active">
  		<%= link_to("Home", home_path) %>
  		</li>
  		<li>

      <% if !logged_in? %>

  			<%= link_to("Login", login_path) %>
        <li> <%= link_to("Signup", signup_path) %>  </li>  

      <% end %>

  		</li>

      <% if logged_in? %>

  		  	<li><%= link_to("Logout", logout_path, method: :delete) %></li>
      <% end %>

  		

  	</ul>
  </nav>

<%= yield %>

</body>
</html>

app/views/users/afterlog.html.erb
<div class="container">
	
	<div class="col-md-offset-4">


		<h1> You have been logged in</h1>
	</div>
</div>

app/views/users/home.html.erb
<div class="container">
	
	<div class="col-md-offset-4">
		<h1> This is home page</h1>
	</div>
</div>

app/views/users/new.html.erb
<div class="container newpage" >


	<div class="col-md-3 col-md-offset-4" style="border:1px solid #e3e3e3">
		

		<%= form_for(@user) do |f|%>

		<div class="field">
			<%= f.label :first_name %>
			<%= f.text_field :first_name , class: 'form-control' %>
		</div>

		<div class="field">
			<%= f.label :last_name %>		
			<%= f.text_field :last_name, class: 'form-control' %>
		</div>

		<div class="field">
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
		</div>

		<div class="field">
			<%= f.label :password %> 
			<%= f.password_field :password ,class: 'form-control' %>
		</div>
		<br> 
		
		<div class="actions">
			<%= f.submit "Submit", class: 'form-control  btn-block btn-primary' %>
		</div>
		<% end %>



	</div>
</div>